export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const PAYMENT_PROCESSING = "PAYMENT_PROCESSING";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";

export const PAYMENT_UPDATING = "PAYMENT_UPDATING";
export const PAYMENT_UPDATE_FAILED = "PAYMENT_UPDATE_FAILED";
export const PAYMENT_UPDATED = "PAYMENT_UPDATED";

export const PAYMENT_CANCELING = "PAYMENT_CANCELING";
export const PAYMENT_CANCELING_FAILED = "PAYMENT_CANCELING_FAILED";
export const PAYMENT_CANCELED = "PAYMENT_CANCELED";

export const FETCHING_TOKEN = "FETCHING_TOKEN";
export const FETCHED_TOKEN = "FETCHED_TOKEN";
export const FETCHING_ERROR = "FETCHING_ERROR";

export const LICIENSES_LOADED = "LICIENSES_LOADED";
export const LICIENSES_LOADING = "LICIENSES_LOADING";

export const FLASH_MESSAGE = "FLASH_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";